{{- if .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-sa
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId }}
  labels:
    azure.workload.identity/use: "true"
{{- end }}
